# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Importaciones:**

In [1]:
import numpy as np
from random import randint

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [3]:
#todo: 
print(np.arange(0, 10, 1))


[0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [11]:
#todo:
array = np.zeros((5))
print(array)
array[2] = 5
print(array)



[0. 0. 0. 0. 0.]
[0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [13]:
#todo: 
array1 = np.random.uniform(0, 1, (3, 3)) #especificamos primero el rango y la forma de la matriz
print(array1)

[[0.64919493 0.50098937 0.04844564]
 [0.9863562  0.88257942 0.7725535 ]
 [0.75996984 0.08690798 0.67317068]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [ ]:
#todo:
#1
arr = np.array([10, 20, 30, 40, 50])
suma = arr + 5
print(suma) 
#2
numero_aletorio = randint(0, 20)
print(numero_aletorio) #Mostramos el nuemro aleatorio 
multiplicacion = arr * numero_aletorio
print(multiplicacion)

[15 25 35 45 55]
3
[ 30  60  90 120 150]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [ ]:
#todo:
array2 = np.eye(4, 4) #matriz identidad de 4x4
print(array2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [27]:
#todo: 
array3 = np.arange(0, 21, 2) #arreglo de 0 a 20 con paso de 2
print(array3)

suma = np.sum(array3) 
print(suma)
resta = np.subtract(array3, 1) 
print(resta) 
multiplicacion = np.multiply(array3, 1)
print(multiplicacion)
division = np.divide(array3, 2)
print(division)

[ 0  2  4  6  8 10 12 14 16 18 20]
110
[-1  1  3  5  7  9 11 13 15 17 19]
[ 0  2  4  6  8 10 12 14 16 18 20]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
